FROM openjdk:17-jdk-alpine
LABEL authors="mfaneli"

RUN mkdir -p /opt/app
WORKDIR /opt/app

ARG SPRING_DATASOURCE_URL
ARG SPRING_DATASOURCE_USERNAME
ARG SPRING_DATASOURCE_PASSWORD

ENV SPRING_DATASOURCE_URL=$SPRING_DATASOURCE_URL
ENV SPRING_DATASOURCE_USERNAME=$SPRING_DATASOURCE_USERNAME
ENV SPRING_DATASOURCE_PASSWORD=$SPRING_DATASOURCE_PASSWORD

COPY . .

RUN chmod +x ./gradlew
RUN ./gradlew build

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "-XX:+UseContainerSupport", "-Xmx512m", "-Xms256m", "build/libs/usuarios-0.0.1-SNAPSHOT.jar"]